# Generated by Django 4.2.14 on 2025-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangobackend", "0016_booking_status_alter_booking_tour"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(default="pending", max_length=15),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
